### ISSUE TITLE
Prototype R&D - Diamond, governance token system; contracts + js interaction

### ISSUE THREAD

**Issue by tjvsx** [0xHabitat/mvp#4]
### ⚡️ Challenge:

Retroactive bounty. Research and develop: the fundamental techniques and patterns of diamond management, the fundamentals of token management via diamond-DAO, and optimal proxy patterns for factories. 

### 🦋 Desired Outcome

Finalize a prototype that allows for:
1. gradual diamond ownership evolution- single-user => multisig => DAO
2. Management of token via basic governance voting
3. Management of diamond's facets via basic governance voting
4. Forking/cloning the diamond via off-chain view function calls and constructor cuts
5. Cloning the diamond via normal proxy
6. Cloning proposalContracts via proxy / minimal proxy for dirt cheap proposal creation

### 🎯 Action Points:

Parts 1-6 complete. 
Additional steps taken-
- created a multisig factory whose sole purpose is receiving upgrade credits and upgrading the diamond
- implemented a repository which holds upgrades ready to be proposed

### 🏆 Reward + Contributor involved

Bounty Size: L
0.35 ETH

Gardener - @tjvsx 0%
Worker - @tjvsx 80% -- 0.28 ETH
Reviewer - @roleengineer  20% -- 0.07 ETH

*adjustable reward/contributors, if there are other interested parties

**Comment by tjvsx** [comment]
hey @roleengineer - 

steps 2&3 are here using the 'execute()' function - https://github.com/tjvsx/habitat-governance/blob/main/contracts/facets/Governance.sol#L75-L77
... which is calling a contract in the /upgrades folder
ex: TokenMinter: https://github.com/tjvsx/habitat-governance/blob/main/contracts/upgrades/proposals/TokenMinter.sol
ex: https://github.com/tjvsx/habitat-governance/blob/main/contracts/upgrades/diamantaires/Diamantaire.sol
but all of these new contract deployments are expensive, so I'm looking into using Minimal Proxies with this design

step 4 we also completed with gemcutter - it's simple js but is expensive
here is an example using solidstate's 'opinionated' diamond implementation:
```
        // get facets
        const facets = await diamond.facets();

        // convert to facetCuts[] objects
        let facetCuts = [];
        let target;
        let selectors;
        let action = 0;
        for (let i = 0; i < facets.length; i++) {
          target = facets[i].target;
          selectors = facets[i].selectors;
          facetCuts.push({
            target,
            action,
            selectors
          })
        }

        //deploy new diamond contract with cuts in constructor
        const NewDiamondFactory = await ethers.getContractFactory('Gem');
        const newdiamond = await NewDiamondFactory.deploy(facetCuts);
        await newdiamond.deployed();
```

**Comment by tjvsx** [comment]
@roleengineer and yes would be happy for you to take the reviewer role!

**Comment by tjvsx** [comment]
step 5 - cloning diamond via normal proxy
```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import { Proxy } from "@solidstate/contracts/proxy/Proxy.sol";
import { OwnableStorage } from "@solidstate/contracts/access/OwnableStorage.sol";
import { IDiamondLoupe } from "@solidstate/contracts/proxy/diamond/IDiamondLoupe.sol";

import 'hardhat/console.sol';

contract DiamondProxy is Proxy {
    address private immutable _impl;

    constructor(address implementation) {
        _impl = implementation;
        OwnableStorage.layout().owner = msg.sender;
    }

    function _getImplementation() internal view override returns (address) {
        return IDiamondLoupe(_impl).facetAddress(msg.sig);
    }
}
```

**Comment by tjvsx** [comment]
major change: This [UpgradeProposalRegistry contract](https://github.com/tjvsx/habitat-governance/blob/main/contracts/upgrades/registry/UpgradeProposalRegistry.sol) replaces *Diamantaire contracts*. 
* It allows for Governance.sol to propose and pass any arbitrary facetCuts of any facetCut[] length. 
* It emits an event that can be utilized to compile a library of diamond upgrades (facetCuts). 

The next step is to allow an *upgrade initializer* (initializes state of diamond on upgrade) to declare arbitrary data with transparency

**Comment by roleengineer** [comment]
i haven't look yet. hope on this weekend i'll find some time

**Comment by tjvsx** [comment]
@roleengineer I think a full review will be easiest once NatSpec comments are added. I expect to be finished within a week or so, at which point I'll provide them, but feel free to approach however you like

**Comment by tjvsx** [comment]
Conclusion [README](https://github.com/0xHabitat/mvp/blob/governance_expirements/README.md) for the governance_experiments branch. NatSpec comments were also added to the contract code where it was necessary
